spring.application.name=currency-api
server.port=8100

spring.datasource.url=jdbc:postgresql://localhost/db_currency
spring.datasource.username=postgres
spring.datasource.password=postegres

spring.cloud.consul.host=localhost
spring.cloud.consul.port=8500

spring.config.import=optional:consul:
